version: "3"
services:
  local-mongodb-mongodb.dev:
    image: 'bitnami/mongodb:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - './mongodb:/bitnami'

  local-rabbit-rabbitmq.dev:
    hostname: local-rabbit-rabbitmq.dev
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_USERNAME=admin
    volumes:
      - './rabbitmq:/bitnami'
    depends_on: 
      - local-mongodb-mongodb.dev

  catanie:
    build: 
      context: catanie
      dockerfile: Dockerfile.catanie
    image: garethcmurphy/catanie
    ports:
      - '4200:80'
    depends_on: 
      - local-rabbit-rabbitmq.dev
      - local-mongodb-mongodb.dev

  catamel:
    build: 
      context: catamel
      dockerfile: Dockerfile.catamel
    image: garethcmurphy/catamel
    ports:
      - '3001:3000'
    depends_on: 
      - local-mongodb-mongodb.dev
      - local-rabbit-rabbitmq.dev
      - catanie
      - myshell
    links:
      - local-mongodb-mongodb.dev
 
  myshell:
    build:
      context: myshell
    image: garethcmurphy/myshell
    depends_on: 
      - local-mongodb-mongodb.dev
      - local-rabbit-rabbitmq.dev
    

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
