version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  catanie:
    build: 
      context: catanie
      dockerfile: Dockerfile.catanie
    image: garethcmurphy/catanie

  catamel:
    build: catamel
    image: garethcmurphy/catamel

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
